# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-03 23:47
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
import rest_framework.utils.encoders
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('contentcuration', '0125_user_feature_flags_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='Change',
            fields=[
                ('server_rev', models.BigAutoField(primary_key=True, serialize=False)),
                ('client_rev', models.IntegerField(blank=True, null=True)),
                ('table', models.CharField(max_length=32)),
                ('change_type', models.IntegerField()),
                ('kwargs', django.contrib.postgres.fields.jsonb.JSONField(encoder=rest_framework.utils.encoders.JSONEncoder)),
                ('applied', models.BooleanField(default=False)),
                ('errored', models.BooleanField(default=False)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contentcuration.Channel')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes_by_user', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sessions.Session')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changes_about_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
